language: ruby
rvm:
  - 2.2
#before_script:
#- gemとか入れるときに使う

script:
- ruby sample.rb
#after_success:

notifications:
    email: tarosa.y@gmail.com
        on_success: change
        on_failure: always
